---
# tasks file for php

- name: Install php extensions
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - php8.0
    - php8.0-mysql
    - php8.0-gd
    - php-ssh2
    - php8.0-mcrypt

- name: Setup php-fpm
  replace: dest=/etc/php/7.0/fpm/php.ini regexp="(;cgi.fix_pathinfo=1)" replace="cgi.fix_pathinfo=0"
  notify:
    - restart nginx
  become: yes

- name: Add php settings
  template: src=../../nginx/templates/nginx-wp-common.conf dest=/etc/nginx/nginx-wp-common.conf owner=www-data group=www-data mode=0644
  notify:
    - restart nginx
  become: yes
